management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,bus-env
spring:
  cloud:
    config:
      server:
        git:
          uri: http://git.tsingzone.com/public-server/configuration-dev.git
          username: Zephyr
          password:
  kafka:
    bootstrap-servers: 192.168.11.91:9092
    producer:
      properties:
        partitioner:
          class: org.apache.kafka.clients.producer.internals.DefaultPartitioner
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  security:
    user:
      password:

server:
  port: 8888
