spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200

dubbo:
    protocol:
        name:
logging:
  level:
    org.elasticsearch.client.*: debug
    org.springframework.data.elasticsearch: debug
