management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,bus-env
spring:
  cloud:
    config:
      server:
        git:
          uri: http://git.tsingzone.com/public-server/configuration-dev.git
          username: Zephyr
          password:
  kafka:
    bootstrap-servers: 192.168.2.55:9092
  security:
    user:
      password:

server:
  port: 8888