# using handler.yml to define the middleware handler chains instead of service.yml

# Handler middleware chain configuration
#----------------------------------------
enabled: true

# Configuration for the LightHttpHandler. The handler is the base class  for all middleware, server and health handlers
# set the Status Object in the AUDIT_INFO, for auditing purposes
# default, if not set:false
auditOnError: ${handler.auditOnError:true}

# set the StackTrace in the AUDIT_INFO, for auditing purposes
# default, if not set:false
auditStackTrace: ${handler.auditStackTrace:false}

#------------------------------------------------------------------------------
# Support individual handler chains for each separate endpoint. It allows framework
# handlers like health check, server info to bypass majority of the middleware handlers
# and allows mixing multiple frameworks like OpenAPI and GraphQL in the same instance.
#
# handlers  --  list of handlers to be used across chains in this microservice
#               including the routing handlers for ALL endpoints
#           --  format: fully qualified handler class name@optional:given name
# chains    --  allows forming of [1..N] chains, which could be wholly or
#               used to form handler chains for each endpoint
#               ex.: default chain below, reused partially across multiple endpoints
# paths     --  list all the paths to be used for routing within the microservice
#           ----  path: the URI for the endpoint (ex.: path: '/v1/pets')
#           ----  method: the operation in use (ex.: 'post')
#           ----  exec: handlers to be executed -- this element forms the list and
#                       the order of execution for the handlers
#
# IMPORTANT NOTES:
# - to avoid executing a handler, it has to be removed/commented out in the chain
#   or change the enabled:boolean to false for a middleware handler configuration.
# - all handlers, routing handler included, are to be listed in the execution chain
# - for consistency, give a name to each handler; it is easier to refer to a name
#   vs a fully qualified class name and is more elegant
# - you can list in chains the fully qualified handler class names, and avoid using the
#   handlers element altogether
#------------------------------------------------------------------------------
handlers:
  # Light-framework cross-cutting concerns implemented in the microservice
#  - com.networknt.traceability.TraceabilityHandler@traceability
#  - com.networknt.correlation.CorrelationHandler@correlation
#  - com.networknt.openapi.JwtVerifyHandler@security
  - learn.light4j.custom.CustomExceptionHandler@exception
  - com.networknt.openapi.OpenApiHandler@specification
  - learn.light4j.custom.CustomJwtVerifyHandler@security
  - learn.light4j.custom.CustomMetricsHandler@metrics
  - com.networknt.body.BodyHandler@body
#  - com.networknt.audit.AuditHandler@audit
  # DumpHandler is to dump detail request/response info to log, useful for troubleshooting but not suggested to use in production due to it may lower the performance
#  - com.networknt.dump.DumpHandler@dump
#  - com.networknt.sanitizer.SanitizerHandler@sanitizer
  - com.networknt.openapi.ValidatorHandler@validator
  # Customer business domain specific cross-cutting concerns handlers
  # - com.example.validator.CustomizedValidator@custvalidator
  # Framework endpoint handlers
#  - com.networknt.health.HealthGetHandler@health
#  - com.networknt.info.ServerInfoGetHandler@info
  - com.networknt.specification.SpecDisplayHandler@spec
  - com.networknt.specification.SpecSwaggerUIHandler@swaggerui
  # - com.networknt.metrics.prometheus.PrometheusGetHandler@getprometheus
  # Business Handlers
  - learn.light4j.handler.JwtTokenGenerateHandler
  - learn.light4j.handler.KafkaProducerHandler


chains:
  default:
    - exception
    - metrics
#    - traceability
#    - correlation
    - specification
    - security
    - body
#    - audit
#    - dump
#    - sanitizer
    - validator
  no_security:  # Don't valid jwt token
    - exception
    - metrics
    - specification
    - body
    - validator

paths:
  - path: '/event-tracking/token'
    method: 'POST'
    exec:
      - no_security
      - learn.light4j.handler.JwtTokenGenerateHandler
  - path: '/event-tracking/kafka'
    method: 'POST'
    exec:
      - default
      - learn.light4j.handler.KafkaProducerHandler
#  - path: '/v1/pets/{petId}'
#    method: 'DELETE'
#    exec:
#      - default
#      - learn.light4j.handler.PetsPetIdDeleteHandler

#  - path: '/health/${server.serviceId:learn.light4j-1.0-SNAPSHOT}'
#    method: 'get'
#    exec:
#      - health

# A handler endpoint that output all the installed components and their configurations
#  - path: '/server/info'
#    method: 'get'
#    exec:
#      - info


# - swaggerui handler need /spec.yaml to load yaml config content
  - path: '/spec.yaml'
    method: 'get'
    exec:
      - spec
  - path: '/specui.html'
    method: 'get'
    exec:
      - swaggerui